name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-2019

    env:
      VCPKG_ROOT: C:\vcpkg-build-cache\vcpkg
      VCPKG_VERSION: "66bac12" # https://github.com/microsoft/vcpkg/commit/0bf3923f9fab4001c00f0f429682a0853b5749e0

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install vcpkg
      - name: Install vcpkg
        shell: cmd
        run: |
          git clone -q https://github.com/microsoft/vcpkg.git %VCPKG_ROOT%
          cd /d %VCPKG_ROOT%
          git checkout %VCPKG_VERSION%
          %VCPKG_ROOT%\bootstrap-vcpkg.bat

      # Install packages
      - name: Install vcpkg Packages
        env:
          VCPKG_PACKAGES: |
            arrayfire
            boost-algorithm
            boost-compute
            boost-filesystem
            boost-lexical-cast
            boost-math
            boost-system
            bullet3
            ccd
            cereal
            eigen3
            entt
            fcl
            fmt
            spdlog
            yaml-cpp
          VCPKG_PACKAGES_NOT_INSTALLABLE: |
            tbb
        shell: cmd
        run: |
          %VCPKG_ROOT%\vcpkg.exe install --recurse --triplet x64-windows %VCPKG_PACKAGES%

      # Remove temporary files
      # https://github.com/Microsoft/vcpkg/blob/master/docs/about/faq.md#how-can-i-remove-temporary-files
      - name: Cleanup vcpkg Temporary Files
        shell: cmd
        run: |
          RMDIR /Q/S %VCPKG_ROOT%\buildtrees
          RMDIR /Q/S %VCPKG_ROOT%\packages
          RMDIR /Q/S %VCPKG_ROOT%\downloads

      - name: Upload artifact
        if: github.event_name == 'release'
        uses: actions/upload-artifact@v2
        with:
          name: vcpkg-build-cache
          path: C:\vcpkg-build-cache\vcpkg

      - name: Prepare Release File
        if: github.event_name == 'release'
        shell: cmd
        run: |
          7z a vcpkg-build-cache.zip %VCPKG_ROOT%

      - name: Upload Release Asset
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./vcpkg-build-cache.zip
          asset_name: vcpkg-build-cache.zip
          asset_content_type: application/zip
